### ISSUE TITLE
Update home page content

### ISSUE THREAD

**Issue by Cassie-Andrews** [Cassie-Andrews/com6338-10-10-andrews-torna#10]
- [x] #45
- [x] check that the stylesheet is linked properly in the HTML file
- [x] add website title to nav and footer 
- [x] determine hero section content - bg image, headline, and subtitle
- [x] determine page content - _maybe some kind of preview or image directing the user to each section (Spotify and Ticketmaster)? May be redundant but would keep the page from looking too sparse if we can't think of anything else_

**Comment by gabster1313** [comment]
I added a logo as the site title and updated our footer
