### ISSUE TITLE
JavaScript Navigation updates

### ISSUE THREAD

**Issue by Cassie-Andrews** [Cassie-Andrews/com6338-10-10-andrews-torna#23]
The last update I pushed:
- Created index.js to handle the navigation's menu button
- Updated CSS file for resizing the nav
- Minor tweaks to the header section on the index.html file for the nav bar

If those updates seem good then we just have to:
- [x] Copy over the updated header code from the index.html to the spotify and ticketmaster HTML files
- [x] Add a script tag linking to the index.js file to the bottom of the body tags on the spotify and ticketmaster HTML files
- [ ] I feel like I'm forgetting something but I think that's it !!

**Comment by gabster1313** [comment]
I update the html on everything and its working fine so far only issue is on the Ticketmaster page the hamburger menu not showing up smh I mightt have missed linking the index.js
