### ISSUE TITLE
Navigation Bar Styling

### ISSUE THREAD

**Issue by gabster1313** [Cassie-Andrews/com6338-10-10-andrews-torna#5]
- [x] Logo for our site is included
- [x] Hamburger menu for mobile responsive
- [x] make sure all tabs are linked correctly 
- [x] A tab for Home, Spotify and Ticketmaster are included

**Comment by gabster1313** [comment]
tabs and logo added, need help with mobile responsive

**Comment by Cassie-Andrews** [comment]
> tabs and logo added, need help with mobile responsive

I can try to help! Can you make a pull request for the changes you made so far so I can see them too?

**Comment by gabster1313** [comment]
@Cassie-Andrews I pushed over twice my stuff and now I'm looking at it and I see nothing went through so I'm gonna push again let me know if you can see it this time #pain
